//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR7
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_population
    {
        public int id_population { get; set; }
        public Nullable<decimal> strength { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> nationalityID { get; set; }
    
        public virtual country country { get; set; }
        public virtual nationality nationality { get; set; }
    }
}
