//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR7
{
    using System;
    using System.Collections.Generic;
    
    public partial class nationality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nationality()
        {
            this.C_population = new HashSet<C_population>();
        }
    
        public int id_nationality { get; set; }
        public string language_of_nationality { get; set; }
        public string name_of_nationality { get; set; }
        public Nullable<decimal> total_strength { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_population> C_population { get; set; }
    }
}
